name: CI Workflow

# trigger
on:
  pull_request:
    branches:
      - main
      - features

jobs:
  build:
    name: Build Next App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install

      - name: Cache the Vendor
        uses: actions/cache@v4.0.2
        with:
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          path: node_modules

  test:
    name: Test Next App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore the Cache
        uses: actions/cache@v4.0.2
        with:
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          path: node_modules

      - name: Install dependencies
        run: |
          npm install

      - name: Unit Testing
        run: |
          npm test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-southeast-1
    