name: CI Workflow

# trigger
on:
  pull_request:
    branches:
      - main
      - features

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/build.yaml
    with:
      version: "8.2"

  test:
    name: "Test"
    uses: ./.github/workflows/test.yaml
    needs: [build]
    secrets:
      aws-key-id: ${{ secrets.AWS_KEY_ID }}
      aws-access-key-id: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
    with:
      version: "8.2"