name: CI Workflow

# trigger
on:
  pull_request:
    branches:
      - main
      - features

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/build.yaml
    with:
      version: "8.2"

  test:
    name: "Test"
    uses: ./.github/workflows/test.yaml
    needs: [build]
    with:
      version: "8.2"