on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  test:
    name: Build Next App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore the Cache
        id: cache
        uses: actions/cache@v4.0.2
        with:
          path: ./node_modules
          key: ${{ github.sha }}-next-dependencies

      - name: Unit Testing
        run: |
          npm test
          npm run build

      - name: Upload to S3 AMZ
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: './.next'

      
           