on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  test:
    name: Build Next App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore the Cache
        id: cache
        uses: actions/cache@v4.0.2
        with:
          path: ./node_modules
          key: ${{ github.sha }}-next-dependencies