on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  test:
    name: Build Next App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore the Cache
        id: cache
        uses: actions/cache@v4.0.2
        with:
          path: ./node_modules
          key: ${{ github.sha }}-next-dependencies

      - name: Unit Testing
        run: |
          npm test
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.aws-key-id }}
          aws-secret-access-key: ${{ secrets.aws-access-key-id}}
          aws-region: ap-southeast-1
      
  

      
           